package adapters;

import com.github.javafaker.Faker;
import dto.Project;

public class ProjectFactory {
    Faker faker = new Faker();
    String code = new Faker().bothify("??");
    String title = new Faker().lorem().sentence();

    public static Project getRandom() {
        Project project = Project.builder()
                .code("hj") //RANDOM CODE GENERATED BY FAKER
                .title("AMAZING QASE PROJECT API") //RANDOM TITLE GENERATED BY FAKER
                .build();
        return project;
    }
}
