import dto.Project;

public class ProjectFactory {
    public static Project getRandom() {
        Project project = Project.builder()
                .code("qwerty") //RANDOM CODE GENERATED BY FAKER
                .title("AMAZING QASE PROJECT API") //RANDOM TITLE GENERATED BY FAKER
                .build();
        return project;
    }
}
